# Generated by Django 3.0.8 on 2020-07-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlor', '0002_icecreame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecreame',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
